# Seconda lezione

In [41]:
# THIS CELL it loads some style files 
from IPython.core.display import HTML
with open( '../lezioni/style/custom.css', 'r' ) as f: html_style = f.read()
HTML( html_style )

In [53]:
import pandas as pd
df = pd.read_csv("../dati/Cork_Airport.csv", 
                 skiprows=24, 
                 usecols=['date', 'maxtp', 'mintp'],
                )
df.tail(2)

              date  maxtp  mintp
20848  30-jan-2019    3.4   -2.1
20849  31-jan-2019    6.4    1.3

## Filtrare righe di un dataframe

In [32]:
max28 = df['maxtp'] >= 28
df[max28]

              date  maxtp  mintp
7863   13-jul-1983   28.4   16.9
7864   14-jul-1983   28.7   19.0
10059  17-jul-1989   28.1   15.0
12267  03-aug-1995   28.0   17.2

Tra vettori a valori Booliani (vero o falso) possiamo fare le seguenti operazioni

`&` congiunzione (un **e**)

`|` disgiunzione (un o non esclusivo)

`~` negazione

In [35]:
min08 = df['mintp'] <= -8
df[max28 | min08]

              date  maxtp  mintp
2604   17-feb-1969    2.3   -8.6
6209   01-jan-1979   -0.4   -8.5
7863   13-jul-1983   28.4   16.9
7864   14-jul-1983   28.7   19.0
9142   12-jan-1987   -2.2   -8.0
10059  17-jul-1989   28.1   15.0
12267  03-aug-1995   28.0   17.2

In [56]:
feb29 = df['date'].map(lambda x: '29-feb' in x)
df[feb29]

              date  maxtp  mintp
789    29-feb-1964    9.5    0.7
2250   29-feb-1968    6.6    3.2
3711   29-feb-1972    8.7    1.6
5172   29-feb-1976   11.5    1.7
6633   29-feb-1980    8.4    5.8
8094   29-feb-1984   11.3    2.1
9555   29-feb-1988    7.2    2.0
11016  29-feb-1992    9.5    7.2
12477  29-feb-1996    9.3    0.7
13938  29-feb-2000    9.4    4.7
15399  29-feb-2004    5.9   -1.7
16860  29-feb-2008   12.2    2.9
18321  29-feb-2012   10.8    7.9
19782  29-feb-2016    9.9    1.9

## I dati temporali

La prima colonna contiene delle date. Però per `Python` queste sono solo delle stringhe di caratteri. 

Possiamo forzare `Python` a leggerle come date.

In `Python` la libreria standard che tratta dati temporali è `datetime`. Parti di questa libreria sono incorporati in `pandas`.

In [58]:
df1 = df.copy()
df1['date'] = pd.to_datetime(df1['date'])
df1

            date  maxtp  mintp
0     1962-01-01    2.8   -2.5
1     1962-01-02    2.8   -3.7
2     1962-01-03    2.3   -3.8
3     1962-01-04    6.6    0.6
4     1962-01-05    9.3    0.6
5     1962-01-06   10.3    8.7
6     1962-01-07    9.6    4.4
7     1962-01-08    9.0    1.2
8     1962-01-09    6.6    2.2
9     1962-01-10   10.4    1.4
10    1962-01-11    7.8    3.0
11    1962-01-12    6.9    1.0
12    1962-01-13    5.9    0.8
13    1962-01-14    5.6    0.0
14    1962-01-15    9.3    2.8
15    1962-01-16    7.3    0.6
16    1962-01-17    8.4    2.2
17    1962-01-18    8.1    1.7
18    1962-01-19    8.3    2.9
19    1962-01-20    9.5    6.0
20    1962-01-21    9.4    1.7
21    1962-01-22    6.7    0.6
22    1962-01-23   10.3    1.7
23    1962-01-24   10.3    7.3
24    1962-01-25   11.6    5.9
25    1962-01-26   10.1    6.5
26    1962-01-27   11.3    8.3
27    1962-01-28   10.3    7.2
28    1962-01-29    8.3    5.7
29    1962-01-30    9.1    6.1
...          ...    ...    ...
20820 2019-01-02    7.5    6.3
20821 2019-01-03    7.5    6.3
20822 2019-01-04    7.6    6.1
20823 2019-01-05    8.3    6.2
20824 2019-01-06   10.0    6.6
20825 2019-01-07   11.0    9.1
20826 2019-01-08   10.1    7.2
20827 2019-01-09   10.2    7.7
20828 2019-01-10   10.7    8.3
20829 2019-01-11   10.3    7.8
20830 2019-01-12    9.9    7.6
20831 2019-01-13   10.9    7.6
20832 2019-01-14    8.8    4.6
20833 2019-01-15    9.1    4.3
20834 2019-01-16    8.4    2.2
20835 2019-01-17    5.5    1.1
20836 2019-01-18    8.3    2.6
20837 2019-01-19    8.1    3.9
20838 2019-01-20    7.2    1.9
20839 2019-01-21    6.6   -0.1
20840 2019-01-22    4.6   -0.5
20841 2019-01-23    8.8    3.6
20842 2019-01-24   10.7    8.7
20843 2019-01-25   10.6    5.5
20844 2019-01-26    9.5    3.9
20845 2019-01-27    6.4    3.0
20846 2019-01-28    6.3    2.5
20847 2019-01-29    4.0   -2.0
20848 2019-01-30    3.4   -2.1
20849 2019-01-31    6.4    1.3

[20850 rows x 3 columns]

            date  maxtp  mintp
0     1962-01-01    2.8   -2.5
1     1962-01-02    2.8   -3.7
2     1962-01-03    2.3   -3.8
3     1962-01-04    6.6    0.6
4     1962-01-05    9.3    0.6
5     1962-01-06   10.3    8.7
6     1962-01-07    9.6    4.4
7     1962-01-08    9.0    1.2
8     1962-01-09    6.6    2.2
9     1962-01-10   10.4    1.4
10    1962-01-11    7.8    3.0
11    1962-01-12    6.9    1.0
12    1962-01-13    5.9    0.8
13    1962-01-14    5.6    0.0
14    1962-01-15    9.3    2.8
15    1962-01-16    7.3    0.6
16    1962-01-17    8.4    2.2
17    1962-01-18    8.1    1.7
18    1962-01-19    8.3    2.9
19    1962-01-20    9.5    6.0
20    1962-01-21    9.4    1.7
21    1962-01-22    6.7    0.6
22    1962-01-23   10.3    1.7
23    1962-01-24   10.3    7.3
24    1962-01-25   11.6    5.9
25    1962-01-26   10.1    6.5
26    1962-01-27   11.3    8.3
27    1962-01-28   10.3    7.2
28    1962-01-29    8.3    5.7
29    1962-01-30    9.1    6.1
...          ...    ...    ...
20820 2019-01-02    7.5    6.3
20821 2019-01-03    7.5    6.3
20822 2019-01-04    7.6    6.1
20823 2019-01-05    8.3    6.2
20824 2019-01-06   10.0    6.6
20825 2019-01-07   11.0    9.1
20826 2019-01-08   10.1    7.2
20827 2019-01-09   10.2    7.7
20828 2019-01-10   10.7    8.3
20829 2019-01-11   10.3    7.8
20830 2019-01-12    9.9    7.6
20831 2019-01-13   10.9    7.6
20832 2019-01-14    8.8    4.6
20833 2019-01-15    9.1    4.3
20834 2019-01-16    8.4    2.2
20835 2019-01-17    5.5    1.1
20836 2019-01-18    8.3    2.6
20837 2019-01-19    8.1    3.9
20838 2019-01-20    7.2    1.9
20839 2019-01-21    6.6   -0.1
20840 2019-01-22    4.6   -0.5
20841 2019-01-23    8.8    3.6
20842 2019-01-24   10.7    8.7
20843 2019-01-25   10.6    5.5
20844 2019-01-26    9.5    3.9
20845 2019-01-27    6.4    3.0
20846 2019-01-28    6.3    2.5
20847 2019-01-29    4.0   -2.0
20848 2019-01-30    3.4   -2.1
20849 2019-01-31    6.4    1.3

[20850 rows x 3 columns]